version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://sealawxe:nC_M_9tzMyNkg9F1Jp0UyP-en5OW0Dr2@heffalump.db.elephantsql.com/sealawxe

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: fundfrontier
      POSTGRES_USER: fundfrontier_owner
      POSTGRES_PASSWORD: npg_6zk1mjHpFcWw
    ports:
      - "5432:5432"
