# Generated by Django 5.0.1 on 2024-01-22 01:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_projects', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_flow_year_1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('period', models.IntegerField()),
                ('npv', models.FloatField(blank=True, null=True)),
                ('payback_period', models.IntegerField(blank=True, null=True)),
                ('annualized_npv', models.FloatField(blank=True, null=True)),
                ('consider_further', models.CharField(choices=[('yes', 'Yes'), ('rejected', 'Rejected')], default='yes', max_length=10)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npv.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('amount', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npv.project')),
            ],
        ),
    ]
