# Generated by Django 5.0.1 on 2024-01-20 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npv', '0002_remove_evaluation_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annual_net_cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_net_cashflows', to='npv.project')),
            ],
        ),
    ]
